# -*- coding: utf-8 -*-
"""Yolo_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/178Z5Z9iGlF3lGu8Q2gF8oeak7FzpHK3b
"""

!pip install -q ultralytics opencv-python

import cv2
from ultralytics import YOLO

model = YOLO("yolov8n.pt")

cap = cv2.VideoCapture("/content/cars video for detection.mp4")

if not cap.isOpened():
    print("Error: Cannot open video file")
    exit()

print("Starting detection... Press stop to end")

frame_id = 0

while True:
    ret, frame = cap.read()

    if not ret:
        print("Finished reading video")
        break

    results = model(frame, verbose=False)

    annotated_frame = results[0].plot()

    # Save frames instead of cv2.imshow
    cv2.imwrite(f"output_frame_{frame_id}.jpg", annotated_frame)
    frame_id += 1

cap.release()

print("Detection finished!")
print("Saved output frames as images.")

import cv2
import glob

# Path of saved frames
frame_files = sorted(
    glob.glob("output_frame_*.jpg"),
    key=lambda x: int(x.split("_")[-1].split(".")[0])
)

if len(frame_files) == 0:
    print("❌ No frames found!")
    exit()

# Read first frame to get size
first_frame = cv2.imread(frame_files[0])
height, width, _ = first_frame.shape

# Output video file
output_video = "yolo_output_video.mp4"

fourcc = cv2.VideoWriter_fourcc(*"mp4v")
fps = 20   # you can change this

out = cv2.VideoWriter(output_video, fourcc, fps, (width, height))

for file in frame_files:
    img = cv2.imread(file)
    out.write(img)

out.release()

print("✅ Video created successfully:", output_video)



